// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    MATRIX_ELF, MATRIX_ID
};
use matrix_core::{Outputs, Inputs};
use risc0_zkvm::{default_prover, ExecutorEnv};
use std::time::Instant;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let inp = Inputs::new(2, 3, 4);
    let outputs = matrix_mul(inp);
    println!();
    println!(
        "matrix mul:/n {:?}",
        outputs.data,
    )
}

fn matrix_mul(inp: Inputs) -> Outputs {
    println!("matrix mul for size: {}x{} * {}x{}", inp.m, inp.n, inp.n, inp.p);
    let env = ExecutorEnv::builder()
        .write(&inp)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Produce a receipt by proving the specified ELF binary.
    
    let gen_start_time = Instant::now();
    let prove_info = prover.prove(env, MATRIX_ELF).unwrap();
    let gen_end_time = Instant::now();

    let verify_start_time = Instant::now();
    prove_info.receipt.verify(MATRIX_ID).unwrap();
    let verify_end_time = Instant::now();


    println!("Number of segments: {}", prove_info.stats.segments);
    println!("User cycles: {}", prove_info.stats.user_cycles);
    println!("Gen time elapsed: {:?}", gen_end_time.duration_since(gen_start_time));
    println!("Verify time elapsed: {:?}", verify_end_time.duration_since(verify_start_time));

    prove_info.receipt.journal.decode().unwrap()
}

#[cfg(test)]
mod tests {
    use matrix_core::{Outputs, Inputs};
    use rand::{thread_rng, Rng};

    #[test]
    fn main() {
        let inp: Inputs = Inputs::new(20, 30, 40);
        let outputs: Outputs = super::matrix_mul(inp.clone());

        let check_times = 10;
        for _ in 0..check_times{
            let x: usize = thread_rng().gen_range(0..outputs.m);
            let y: usize = thread_rng().gen_range(0..outputs.p);
            let mut sumup: usize = 0;
            for i in 0..inp.n{
                sumup += inp.data[x*inp.n+i] * inp.data[inp.m*inp.n+i*inp.p+y];
            }
            assert_eq!(
                outputs.data[x*outputs.p+y], sumup,
                "The random selected point verified failed"
            );
        }
        assert_eq!(
            outputs.data.len(), inp.m * inp.p,
            "Output matrix size wrong"
        );
    }
}
